apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketball-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basketball-backend
  template:
    metadata:
      labels:
        app: basketball-backend
    spec:
      containers:
        - name: backend
          image: basketball-backend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
