apiVersion: v1
kind: Service
metadata:
  name: basketball-backend
spec:
  type: NodePort
  selector:
    app: basketball-backend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
